language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "mictaege-github"
    token:
      secure: SONAR_TOKEN

branches:
  only:
    - master
    - develop

script:
  gradle clean test sonarqube
