language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "mictaege-github"
    token:
      secure: $SONAR_TOKEN
    branches:
      - master
      - develop

branches:
  only:
    - master
    - develop

script:
  gradle clean test sonarqube
